[package]
name = "tiny_circle_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.42.1", features = ["bitflags"] }
tiny-skia = "0.11"
image = "0.25"

[lib]
crate-type = ["cdylib"]

# [package.metadata.component]
package = "component:tiny-circle-wasm"
